### ISSUE TITLE
question

### ISSUE THREAD

**Issue by japlic** [Apollo-Roboto/discord.py-ext-prometheus#26]
im using docker how host my discord bot how do i expose the port for prometheus

```yml

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=50
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    ports:
      - "50:50"

  axondb:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: NODB
      POSTGRES_USER: NOUSER
      POSTGRES_PASSWORD: NOPASS
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lavalink

  discord-bot:
    build: .
    container_name: axon
    environment:
      - token=NOTOKENFORYOU
    depends_on:
      - lavalink
      - axondb
    networks:
      - lavalink
    
networks:
  lavalink:
    driver: bridge

volumes:
  pgdata:
```

**Comment by ApolloRoboto** [comment]
The default port is 8000, you can expose it the same way you've exposed your database port.

```yaml
  discord-bot:
    ...
    ports:
      - "8000:8000"
```

Then the metrics should be visible at `http://localhost:8000/metrics`
